## Import Libraries 
Only libraries useful for this project: Matplolib, Pandas, Plotly

In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

## Prepare Data 
Read the CSV file containing the real estate data from Mexico city.

In [20]:
df1 = pd.read_csv("data/mexico-city-real-estate-1.csv")
df1.head()

,operation,property_type,place_with_parent_names,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url
0,sell,apartment,|Miguel Hidalgo|Distrito Federal|México|,"23.634501,-102.552788",5500000.0,MXN,5450245.50,289775.66,NaN,54.0,NaN,101851.851852,NaN,NaN,NaN,http://miguel-hidalgo-df.properati.com.mx/o3zb...
1,sell,house,|Iztapalapa|Distrito Federal|México|,"19.31033,-99.068557",1512000.0,MXN,1498321.97,79661.96,NaN,80.0,NaN,18900.000000,NaN,NaN,NaN,http://iztapalapa.properati.com.mx/q7t0_venta_...
2,sell,apartment,|Tlalpan|Distrito Federal|México|,"19.279771,-99.234597",926667.0,MXN,918284.00,48822.82,NaN,100.0,NaN,9266.670000,NaN,NaN,NaN,http://tlalpan.properati.com.mx/qbi4_venta_dep...
3,sell,apartment,|Miguel Hidalgo|Distrito Federal|México|,"23.634501,-102.552788",6410000.0,MXN,6352013.39,337720.36,NaN,135.0,NaN,47481.481481,NaN,NaN,NaN,http://miguel-hidalgo-df.properati.com.mx/opeq...
4,sell,apartment,|Benito Juárez|Quintana Roo|México|,"21.1902642,-86.8198375",875000.0,USD,16457437.50,875000.00,0.0,263.0,NaN,3326.996198,NaN,NaN,NaN,http://cancun.properati.com.mx/hg4t_venta_depa...

In [21]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4628 entries, 0 to 4627
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   operation                   4628 non-null   str
 1   property_type               4628 non-null   str
 2   place_with_parent_names     4628 non-null   str
 3   lat-lon                     4144 non-null   str
 4   price                       4538 non-null   float64
 5   currency                    4538 non-null   str
 6   price_aprox_local_currency  4538 non-null   float64
 7   price_aprox_usd             4538 non-null   float64
 8   surface_total_in_m2         1668 non-null   float64
 9   surface_covered_in_m2       4436 non-null   float64
 10  price_usd_per_m2            1150 non-null   float64
 11  price_per_m2                4249 non-null   float64
 12  floor                       291 non-null    float64
 13  rooms                       136 non-null    float64
 14  expenses                    5 non-null      float64
 15  properati_url               4628 non-null   str
dtypes: float64(10), str(6)
memory usage: 578.6 KB

### Drop all rows with `NaN` Values from the datafram `df1`

In [22]:
df1.isnull().sum()

operation                        0
property_type                    0
place_with_parent_names          0
lat-lon                        484
price                           90
currency                        90
price_aprox_local_currency      90
price_aprox_usd                 90
surface_total_in_m2           2960
surface_covered_in_m2          192
price_usd_per_m2              3478
price_per_m2                   379
floor                         4337
rooms                         4492
expenses                      4623
properati_url                    0
dtype: int64

In [23]:
df1 = df1.dropna()

In [24]:
df1.isnull().sum()

operation                     0
property_type                 0
place_with_parent_names       0
lat-lon                       0
price                         0
currency                      0
price_aprox_local_currency    0
price_aprox_usd               0
surface_total_in_m2           0
surface_covered_in_m2         0
price_usd_per_m2              0
price_per_m2                  0
floor                         0
rooms                         0
expenses                      0
properati_url                 0
dtype: int64

### Separate `lat-lon` column into two columns `lat` and `lon`
Ensure that the two columns are of `float` data type

In [29]:
# Split once, then assign by list index
# split_coords = df1['lat-lon'].str.split(",")

# df1['lat'] = split_coords.str[0]
# df1['lon'] = split_coords.str[1]

df1.head()

Empty DataFrame
Columns: [operation, property_type, place_with_parent_names, lat-lon, price, currency, price_aprox_local_currency, price_aprox_usd, surface_total_in_m2, surface_covered_in_m2, price_usd_per_m2, price_per_m2, floor, rooms, expenses, properati_url, lat, lon]
Index: []

In [26]:
# View the rows that didn't split properly
df1[df1['lon'].isna()]

Empty DataFrame
Columns: [operation, property_type, place_with_parent_names, lat-lon, price, currency, price_aprox_local_currency, price_aprox_usd, surface_total_in_m2, surface_covered_in_m2, price_usd_per_m2, price_per_m2, floor, rooms, expenses, properati_url, lat, lon]
Index: []

In [27]:
# This will output the dataframe so you can see how many columns it actually created
split_df = df1["lat-lon"].str.split(",", expand=True)
split_df.head()

Empty DataFrame
Columns: []
Index: []

In [28]:
df1.head()

Empty DataFrame
Columns: [operation, property_type, place_with_parent_names, lat-lon, price, currency, price_aprox_local_currency, price_aprox_usd, surface_total_in_m2, surface_covered_in_m2, price_usd_per_m2, price_per_m2, floor, rooms, expenses, properati_url, lat, lon]
Index: []